# Generated by Django 4.2.6 on 2025-03-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.PositiveIntegerField(),
        ),
    ]
