# Generated by Django 4.2.6 on 2025-03-10 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DishesForOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_for_order', to='api.dish')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField()),
                ('total_price', models.IntegerField()),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Ready', 'Ready'), ('Paid', 'Paid')], default='Waiting', max_length=16)),
                ('items', models.ManyToManyField(related_name='order_items', through='api.DishesForOrder', to='api.dish')),
            ],
        ),
        migrations.AddField(
            model_name='dishesfororder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_for_order', to='api.order'),
        ),
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.UniqueConstraint(fields=('name', 'price'), name='unique_name_price'),
        ),
        migrations.AddConstraint(
            model_name='dishesfororder',
            constraint=models.UniqueConstraint(fields=('order', 'dish'), name='unique_dish_order'),
        ),
    ]
